DROP DATABASE IF EXISTS baza;
CREATE DATABASE baza;
GO
USE baza;
GO
CREATE TABLE RESTAURANT (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NAMERES VARCHAR(50) ,
    CITY VARCHAR(50),
    RESTAURANTADD VARCHAR(100) ,
    ZIP VARCHAR(6),
);
GO
CREATE TABLE EMPLOYE_ROLES (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) ,
);
GO
CREATE TABLE EMPLOYE (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY ,
    NAMERES VARCHAR(50) ,
    SURNMAE VARCHAR(50) ,
    PERSID VARCHAR(11),
);
GO
CREATE TABLE RESTAURANT_EMPLOYE (
    RESID INT NOT NULL,
    EMPID INT NOT NULL,
    ROLEID INT NOT NULL,
    PRIMARY KEY (RESID, EMPID),
    FOREIGN KEY (RESID) REFERENCES RESTAURANT(ID),
    FOREIGN KEY (EMPID) REFERENCES EMPLOYE(ID),
    FOREIGN KEY (ROLEID) REFERENCES EMPLOYE_ROLES(ID)
);
GO
CREATE TABLE RESERW (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RESID INT,
    SURNAME VARCHAR(50),
    RESERVDATETIME DATETIME,
    PHONE VARCHAR(18),
    NUMBOFGUEST INT,
    FOREIGN KEY (RESID) REFERENCES RESTAURANT(ID)
);
GO
CREATE TABLE TYPEM (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    title VARCHAR(50) ,
);
GO
CREATE TABLE MEAL (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TYPEID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    FOREIGN KEY (TYPEID) REFERENCES TYPEM(ID)
);
GO